### PR TITLE
Updated logos and fixed size issues with gallery items

### LINKED ISSUE #39: Update Product Documents section
- [ ] Icons need to be updated

- [ ] Tiles need to be the same size

- [ ] Consider removing the number of controls. Maybe place them in the product overview page.

### PR DESCRIPTION
**Pull request by carlosmmatos**
Fixes #39

### CODE REVIEW

**Comment by carlosmmatos** [comment]
Hold off on merging.. Going to try to make all logos more aligned within a specific constraint.

**Comment by carlosmmatos** [comment]
images are much cleaner now - thanks to some gimp skills from the past ;)

**Comment by carlosmmatos** [comment]
Here's a preview of what it now looks like:
image

**Comment by isimluk** [comment]
:clap: !

**Pull request merged**
