### PR TITLE
Let's be in production

### PR DESCRIPTION
**Pull request by redhatrises**

### CODE REVIEW

**Comment by isimluk** [comment]
Wouldn't it be advantageous to make this change in the dockerfile? 

That is what the latest gobuffalo does when you generate new project.

**Comment by isimluk** [comment]
I mean adding

```
ENV GO_ENV=production
```
to the dockerfile achieves the same. While keeping development easy by not requiring developers to redefine the dev variable all the time.

**Comment by redhatrises** [comment]
> I mean adding
> 
> ```
> ENV GO_ENV=production
> ```
> 
> to the dockerfile achieves the same. While keeping development easy by not requiring developers to redefine the env variable all the time.

Changes made

**Comment by isimluk** [comment]
Thanks!

**Pull request merged**
